#
# Makefile for ise_lpm components
#

ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/tinysys_scmi/
ccflags-y += -I$(srctree)/mtk-modules/include/linux/soc/mediatek/

obj-$(CONFIG_MTK_ISE_LPM_SUPPORT) += ise_lpm.o


