# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/mtk-modules/drivers/iommu
ccflags-y += -I$(srctree)/mtk-modules/drivers/clk/mediatek/
ccflags-y += -I$(srctree)/mtk-modules/include/soc/mediatek
ccflags-y += -I$(srctree)/mtk-modules/drivers/iommu/arm/arm-smmu-v3/
obj-$(CONFIG_DEVICE_MODULES_MTK_SMI) += mtk-smi-dbg.o

