# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/smi/
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/cmdq/mailbox/
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/tinysys_scmi/
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/slbc
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/iommu/
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/vcp/rv
ccflags-y += -I$(srctree)/mtk-modules/drivers/misc/mediatek/vcp/include
ccflags-y += -I$(srctree)/mtk-modules/drivers/clk/mediatek

obj-$(CONFIG_MTK_MMINFRA) += mtk-mminfra-debug.o mtk-mminfra-imax.o
obj-$(CONFIG_MTK_MMINFRA) += mm-fake-engine.o
